Default: &defaults
  user: prittorrent
  password: 1234
  host: localhost
  port: 5432
  dbname: prittorrent
  poolsize: 10

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  poolsize: 10
  <<: *defaults

Production4:
  <<: *defaults

Production6:
  <<: *defaults

Production4SSL:
  <<: *defaults

Production6SSL:
  <<: *defaults
