Default: &defaults
  host: "*6"
  port: 8081
  approot: ""
  copyright: APL2

Development:
  approot: "http://localhost:8081"
  <<: *defaults

Production4:
  host: "*4"
  port: 80
  approot: "http://bitlove.org"
  <<: *defaults

Production6:
  host: "*6"
  port: 80
  approot: "http://bitlove.org"
  <<: *defaults
